Repository lightning-js/renderer, pull requests merged in 2023-12, with the labels that each got.

#103 Perf: Implement flag driven update dependency graph
  .gitignore
  README.md
  docs/NodeDependencyGraph.md
  docs/images/dependency-graph.png
  docs/images/dependency-graph.txt
  src/core/CoreNode.ts
  src/core/Stage.ts
  src/core/renderers/webgl/WebGlCoreRenderer.ts
  src/core/text-rendering/renderers/CanvasTextRenderer.ts
  typedoc.config.cjs
Labels: performance

#99 Perf: Pause RAF loop when there are no updates
  examples/index.ts
  src/core/CoreNode.ts
  src/core/CoreTextNode.ts
  src/core/Stage.ts
  src/core/platform.ts
  src/core/renderers/webgl/WebGlCoreRenderer.ts
  src/core/scene/Scene.ts
  src/core/text-rendering/font-face-types/SdfTrFontFace/SdfTrFontFace.ts
  visual-regression/certified-snapshots/chromium-ci/alpha-blending-2.png
Labels: performance

#100 Perf: Skip nodes that have no renderable props.
  src/core/CoreNode.ts
  src/core/CoreTextNode.ts
  src/core/Stage.ts
Labels: performance

#113 Fix issue that caused animations not to finish all the way
  examples/tests/animation.ts
  src/core/animations/CoreAnimation.ts
Labels: bug

#110 Context Spy
  examples/README.md
  examples/common/StatTracker.ts
  examples/index.ts
  src/common/CommonTypes.ts
  src/core/Stage.ts
  src/core/lib/ContextSpy.ts
  src/core/renderers/webgl/WebGlCoreRenderer.ts
  src/main-api/ICoreDriver.ts
  src/main-api/RendererMain.ts
  src/render-drivers/main/MainCoreDriver.ts
  src/render-drivers/threadx/ThreadXCoreDriver.ts
  src/render-drivers/threadx/ThreadXRendererMessage.ts
  src/render-drivers/threadx/worker/renderer.ts
  src/utils.ts
Labels: breaking change!
